### ISSUE TITLE
Add more sorting Algorithms

### ISSUE THREAD

**Issue by ComputerScientist-01** [ComputerScientist-01/Sorting-Visualizer#1]
more sorting algorithms could be added

**Comment by sandip2224** [comment]
How about selection sort?

**Comment by AdityaPrakash-26** [comment]
Selection Sort, Insertion Sort, Merge Sort, and Heap Sort are few of the staple sorting algorithms that you are missing :)

**Comment by divyanshu1810** [comment]
I would like to work on this issue.

**Comment by ComputerScientist-01** [comment]
#2 checks out
